# This file serves for local development. Keep it in sync with antora-playbook.yml.
site:
  title: Documentation
  url: https://www.optaplanner.org/docs
  start_page: optaplanner::planner-introduction/planner-introduction.adoc
  robots: allow
  keys:
    google_analytics: 'G-KJ89NSGDQ9'
content:
  edit_url: '{web_url}/edit/main/{path}'
  sources:
    # Assuming the optaplanner local repository resides next to the optaplanner-website.
    - url: ../../optaplanner
      branches: [HEAD]
      start_path: optaplanner-docs/src
ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
antora:
  extensions:
    - '@antora/lunr-extension'
