= Report an issue
:awestruct-description: Submit issues in JIRA or contribute a pull request on GitHub.
:awestruct-layout: normalBase
:showtitle:

== Issue tracker (JIRA)

*We welcome all issue reports (bugs, improvements, new feature requests, ...) in https://issues.jboss.org/browse/PLANNER[our JIRA issue tracker]*.
Log in and click on the button _Create Issue_.

We prioritize issues based on:

* Is it a link:../community/product.html[customer request]?
* Is there https://github.com/kiegroup/optaplanner/pulls[a Pull Request]?
* Or is there a https://issues.jboss.org/browse/PLANNER[a JIRA issue]? Does it include a reproducer?
* Severity
* How many community users are affected?

We prefer issues with:

* A *clear, specific title*
** Specify the context
** Distinguish between the old behaviour and the desired behaviour: use the words _should_ or _should not_.
** For example:
*** Bad: _OptaPlanner throws a NullPointerException_
*** Good: _Exhaustive Search with FULL_ASSERT should not throw a NullPointerException_
* A clear *reproduce recipe*
** If possible, adjust an existing example to reproduce the issue and attach the modified files to the JIRA issue.
** Otherwise, attach a standalone project zip with a Maven or Gradle file and specify in the JIRA issue which main class to run.

== Pull requests on GitHub

Want to fix the issue yourself? Fork https://github.com/kiegroup/optaplanner[the git repository] and send in a pull request.
We usually process all pull requests within a few days.

*Show https://github.com/kiegroup/optaplanner/pulls[the open pull requests] and https://github.com/kiegroup/optaplanner/pulls?q=is%3Apr+is%3Aclosed[the closed pull requests].*
