= LocalSolver versus OptaPlanner comparison
:jbake-type: competitorBase
:jbake-description: OptaPlanner is a fast, open source alternative to LocalSolver for mathematical optimization.
:jbake-priority: 1.0
:jbake-related_tag: localsolver
:jbake-featured_youtube_id: -7ips_GMFmo

[.lead]
LocalSolver and OptaPlanner are mathematical optimization solvers.
They are both used across the globe in production.
But there are notable differences between OptaPlanner and LocalSolver.

[.lead]
OptaPlanner is <<openSource,open source>>,
<<fasterAndMoreScalable,fast>>, <<fasterAndMoreScalable,scalable>> and
<<easyToUse,easy to use>> because of
<<objectOrientedProgrammingModel,OO models>> and
<<codeConstraint,constraints as code>>.
OptaPlanner is also <<easyToIntegrate, integration friendly>> (including REST)
and <<cloudReady,cloud ready>>. It runs on <<operationSystemIndependent,all operating systems>>.

*Try it yourself.* No license needed. +
*https://www.optaplanner.org/docs/optaplanner/latest/quickstart/quickstart.html[Get started with OptaPlanner today]*
for Java, Kotlin or Scala.
Or https://www.optapy.org[try OptaPy] for Python.


[#openSource]
== OptaPlanner is Open Source

LocalSolver is closed source software.

OptaPlanner is enterprise open source software under the link:../code/license.html[Apache License],
which allows free reuse for commercial purposes.
_All_ of OptaPlanner's source code is available on https://github.com/kiegroup/optaplanner[GitHub].
Its community is _open_. its decision making is _open_.

A dedicated link:../community/team.html[core team] of optimization experts
(employed by https://www.redhat.com[Red Hat]) works full-time on OptaPlanner.
Also hundreds of external developers have contributed to OptaPlanner.
Regardless of who wrote the code, an(other) OptaPlanner core developer has reviewed it
before it is merged into the main repository.

Red Hat also offers link:../product/services.html[support and consulting services]
for customers who want to take their OptaPlanner implementation to the next level.


[#fasterAndMoreScalable]
== OptaPlanner is fast and scalable

// TODO Change to "OptaPlanner is both faster and more scalable than LocalSolver" after adding the open benchmarks as proof.
OptaPlanner is both fast and scalable
for planning and scheduling use cases, such as the link:../learn/useCases/vehicleRoutingProblem.html[Vehicle Routing Problem],
link:../learn/useCases/employeeRostering.html[Employee Rostering] and link:../learn/useCases/maintenanceScheduling.html[Maintenance scheduling].

OptaPlanner delivers better results, in the same amount of CPU time.


[#easyToUse]
== OptaPlanner is easy to use

Any software developer can implement an optimization use case with OptaPlanner.
*There's no need to hire expensive consultants to write complex mathematical equations.*
It's OOP friendly.

Later, when your business reality changes, you can quickly adjust the OptaPlanner constraints.
It is maintenance friendly.

OptaPlanner supports both Object-Oriented Programming and Functional Programming:


[#objectOrientedProgrammingModel]
=== An OptaPlanner model is Object-Oriented Programming (OOP) friendly

Both LocalSolver and OptaPlanner require you to define your model, with _optimization variables_,
so the mathematical optimization software knows which decisions it needs to make.

LocalSolver supports 5 types of optimization variables: booleans, integers, floating point numbers and sets and lists.
You must transform your domain model into those types.
For example:

[source,java]
----
// Input
LSModel model = ...
LSExpression[][] assignments = new LSExpression[shifts.size()][employees.size()];
for (int s = 0; s < shifts.size(); s++) {
    for (int e = 0; e < employees.size(); e++) {
        assignments[s][e] = model.boolVar();
    }
}
... // Add constraints to enforce no shift is assigned to multiple employees

// Solve
model.minimize(...);

// Output
for (int s = 0; s < shifts.size(); s++) {
    for (int e = 0; e < employees.size(); e++) {
        if (assignments[s][e].getValue() == 1) {
            print(shifts[s] + " is assigned to " + employees[e]);
        }
    }
}
----

OptaPlanner supports any type of optimization variables,
including your custom classes (`Employee`, `Vehicle`, ...) or standard classes (`Boolean`, `Integer`, `BigDecimal`, `LocalDate`, ...).
You can reuse your existing domain model, to avoid costly data transformations.
For example:

[source,java]
----
@PlanningEntity
class Shift { // User defined class
    ... // Shift id, date, start time, required skills, ...

    @PlanningVariable
    Employee employee;
}
@PlanningSolution
class TimeTable { // User defined class
    List<Employee> employees;
    List<Shift> shifts;
}

// Input
Timetable timetable = new Timetable(shifts, employees);

// Solve
timetable = Solver.solve(timetable);

// Output
for (Shift shift : timetable.shifts) {
    print(shift + " is assigned to " + shift.employee);
}
----

Neither of these 2 classes (`Shift` and `Timetable`) exist in OptaPlanner itself: you define and shape them.
Your code doesn't deal with booleans and numbers, but uses `Employee`, `Shift` and `DayOfRequest` instances.
Your code reads naturally.

OptaPlanner even supports polymorphism.

[#codeConstraint]
=== OptaPlanner constraints are code, not equations

LocalSolver constraints are implemented as *mathematical equations*.
For example, to assign _at most one shift per day_,
you add an equation `s1 + s2 + s3 \<= 1` for all shifts on day 1,
an equation `s4 + s5 \<= 1` for all shifts on day 2, and so forth:

[source,java]
----
for (int e = 0; e < employees.size(); e++) {
    for (int d = 0; d < dates.size(); d++) {
        LSExpression expr = ...
        for (int s = 0; s < shifts.size(); s++) {
            // If the shift is on the date
            if (shifts[s].date == dates[d])) {
                expr.addOperand(assignments[s][e]);
            }
        }
        model.constraint(model.lq(expr, 1));
    }
}
----

OptaPlanner constraints are implemented as *programming code*.
If you use _ConstraintStreams_, a Functional Programming (FP) approach,
OptaPlanner automatically applies incremental score calculation with deltas
for maximum scalability and performance.

For example, to assign _at most one shift per day_,
select every pair of `Shift` instances
that have the same `date` and the same `employee`,
to penalize matching pairs as a hard constraint:

[source,java]
----
// For every shift ...
constraintFactory.forEach(Shift.class)
    // ... combined with any other shift ...
    .join(Shift.class,
        // ... on the same date ...
        equal(shift -> shift.date),
        // ... assigned to the same employee ...
        equal(shift -> shift.employee))
    // ... penalize one broken hard constraint per pair.
    .penalize(HardSoftScore.ONE_HARD)
    .asConstraint("One shift per day");
----

That `equal()` method accepts _any_ code as a parameter to return _any_ type (not just booleans and numbers).

For example, because `date` is an instance of `LocalDate` (an advanced Date and Time API),
use `LocalDate.isDayOfWeek()` to select 2 shifts on the same day of week:

[source,java]
----
        // ... on the same day of week ...
        equal(shift -> shift.date.getDayOfWeek())
----

https://www.youtube.com/watch?v=-5wpm-gesOY[Date and times arithmetic is notoriously difficult,]
because of Daylight Saving Time (DST), timezones, leap years and other semantics that only a few programmers on this planet actually understand.
OptaPlanner empowers you to directly use their APIs (such as `LocalDate`) in your constraints.

Besides the `equal()` joiner, OptaPlanner supplies `lessThan()`, `greaterThan()`, `lessThanOrEqual()`, `greaterThanOrEqual()`,
`overlapping()`, etc.
OptaPlanner automatically applies indexing (hashtable techniques) on joiners for performance.

For example, select two overlapping shifts with the `overlapping()` joiner
(even if they start or end at different times):

[source,java]
----
        // ... that overlap ...
        overlapping(shift -> shift.startDateTime, shift -> shift.endDateTime)
----

Besides the `join()` construct, OptaPlanner supports `filter()`, `groupBy()`, `ifExists()`, `ifNotExists()`, `map()`, etc.
This rich API empowers you to implement any constraint.

For example, allow employees that can work double shifts to work double shifts
by filtering out all employees that work double shifts with a `filter()`:

[source,java]
----
// For every shift ...
constraintFactory.forEach(Shift.class)
    // ... assigned to an employee that does not work double shifts ...
    .filter(shift -> !shift.employee.worksDoubleShifts)
    // ... combined with any other shift ...
    .join(Shift.class,
        equal(shift -> shift.date),
        // ... assigned to that same employee that does not work double shifts ...
        equal(shift -> shift.employee))
    .penalize(HardSoftScore.ONE_HARD)
    .asConstraint("One shift per day");
----

The `groupBy()` construct supports `count()`, `sum()`, `average()`, `min()`, `max()`, `toList()`, `toSet()`, `toMap()`, etc.
You can also plug in custom collectors.

For example, don't assign more than 10 shifts to any employee by counting their shifts with `count()`:

[source,java]
----
constraintFactory.forEach(Shift.class)
    // Group shifts by employee and count the number of shifts per employee ...
    .groupBy(shift -> shift.employee, count())
    // ... if more than 10 shifts for one employee ...
    .filter((employee, shiftCount) -> shiftCount > 10)
    // ... penalize as a hard constraint ...
    .penalize(HardSoftScore.ONE_HARD,
            // ... multiplied by the number of excessive shifts.
            (employee, shiftCount) -> shiftCount - 10)
    .asConstraint("Too many shifts");
----

OptaPlanner allows weighting constraints dynamically.
It has *no linear limitations*.

For example, avoid overtime and distribute it *fairly* by penalizing the number of excessive hours *squared*:

[source,java]
----
constraintFactory.forEach(Shift.class)
    // Group shifts by employee and sum the shift duration per employee ...
    .groupBy(shift -> shift.employee, sum(shift -> shift.getDurationInHours()))
    // ... if an employee is working more hours than his/her contract ...
    .filter((employee, hoursTotal) -> hoursTotal > employee.contract.maxHours)
    // ... penalize as a soft constraint of weight 1000 ...
    .penalize(HardSoftScore.ofSoft(1000),
            // ... multiplied by the number of excessive hours squared.
            (employee, hoursTotal) -> {
                    int excessiveHours = hoursTotal - employee.contract.maxHours;
                    return excessiveHours * excessiveHours;
            })
    .asConstraint("Too many shifts");
----

This penalizes outliers more.
It automatically load balances overtime in fair manner across the employees,
whenever possible. https://www.optaplanner.org/blog/2017/02/03/FormulaForMeasuringUnfairness.html[Learn more.]

OptaPlanner also supports positive constraints: use `reward()` instead of `penalize()`.


[#easyToIntegrate]
== OptaPlanner is easy to integrate with the REST, databases, etc

The https://github.com/kiegroup/optaplanner-quickstarts[OptaPlanner Quickstarts]
show how to integrate OptaPlanner with various technologies to quickly:

* Expose a REST service and JSON data with link:../compatibility/quarkus.html[Quarkus] or link:../compatibility/springBoot.html[Spring].
* Connect to a relational database with link:../compatibility/quarkus.html[Quarkus] or link:../compatibility/springBoot.html[Spring].
* Load balance solvers across multiple nodes with ActiveMQ.


[#cloudReady]
== OptaPlanner is cloud ready

OptaPlanner runs on all major clouds, such as Amazon AWS, Microsoft Azure, Google Compute Engine and IBM Cloud.
It works on all major cloud technologies, such as Kubernetes, OpenShift, Docker and Virtual Machines.

But it just runs as fine on your local development machine without internet access,
or embedded in a process on-premise.

With link:../compatibility/quarkus.html[Quarkus] it can compile Java and Kotlin code natively for serverless use cases
that need to start up in milliseconds.


[#operationSystemIndependent]
== OptaPlanner runs on all major operating systems

OptaPlanner runs on all major operating systems, such as Linux, Windows and macOS.


== Get started

To get started with OptaPlanner, read the https://www.optaplanner.org/docs/optaplanner/latest/quickstart/quickstart.html[quick start guide]
or copy-paste the source code of one of the https://github.com/kiegroup/optaplanner-quickstarts[OptaPlanner Quickstarts].
