= Release Notes 7.0
:awestruct-description: New and noteworthy, demos and status for OptaPlanner 7.0.
:awestruct-layout: releaseNotesBase
:awestruct-priority: 1.0
:awestruct-release_notes_version: 7.0
:awestruct-release_notes_version_qualifier: Beta

[[NewAndNoteWorthy]]
== New and noteworthy

=== Java 8 or higher

OptaPlanner 7.x now requires Java 8 or higher to run. The 6.x releases remain compatible with Java 6 or higher.

The API and implementation now make use of Java 7 and Java 8 features (such as lamdba's).

=== No longer needed to implement the `Solution` interface

Your solution class no longer needs both have the `@PlanningSolution` annotation and implement the `Solution` interface.
No need to repeat yourself any more.
The `Solution` interface is now deprecated (but still works for backwards compatibility):
only the `@PlanningSolution` annotation suffices.

Instead of implementing the old interface methods, annotate your `Score` getter with `@PlanningScore`.
If you're using Drools score calculation, annotate all problem fact getters (or fields)
with `@ProblemFactCollectionProperty` or `@ProblemFactProperty`.

[source, java]
----
@PlanningSolution
public class CloudBalance {

    private List<CloudComputer> computerList;
    ...

    private HardSoftScore score;

    @ValueRangeProvider(id = "computerRange")
    @ProblemFactCollectionProperty
    public List<CloudComputer> getComputerList() {...}

    @PlanningScore
    public HardSoftScore getScore() {...}
    public void setScore(HardSoftScore score) {...}

}
----

Solving hasn't changed:

[source,java]
----
    SolverFactory<CloudBalance> solverFactory = SolverFactory.createFromXmlResource(...);
    Solver<CloudBalance> solver = solverFactory.buildSolver();
    CloudBalance solvedCloudBalance = solver.solve(unsolvedCloudBalance);
----

Contributed by Lukáš Petrovický.

=== No longer needed to define the score type in the solver configuration

Planner now picks it up automatically from the domain model.

=== New JAXB and Jackson support and improved XStream support

To marshall a `Score` from or to XML or JSON, use the appropriate binder
for XStream, JAXB or Jackson in `optaplanner-persistence-xstream`, `optaplanner-persistence-jaxb` and `optaplanner-persistence-jackson`.

These will create pretty XML:

[source,xml]
----
<CloudBalance>
   ...
   <score>0hard/-200soft</score>
</CloudBalance>
----

And beautiful JSON:

[source,json]
----
{
   ...
   "score":"0hard/-200soft"
}
----

See the documentation on how to configure them.

=== New example: Task assigning

Assign tasks to employee and take into account required skills, affinity with the customer and task priority.
This example also demonstrates real-time producing and consuming of tasks.

+++
<iframe width="853" height="480" src="https://www.youtube.com/embed/ksXjQ851RAU?rel=0" frameborder="0" allowfullscreen></iframe>
+++

=== Other improvements

* Booleans are now supported by `ValueRangeFactory` too: `createBooleanValueRange()`
* Dates and time are now supported by `ValueRangeFactory` too: `createTemporalValueRange()`. Contributed by Kevin Wallis.
* `@ValueRangeProvider` now supports methods that return an array too.
* The log now outputs the score calculation speed for each solver phase too.
