= Release Notes 6.1
:awestruct-description: New and noteworthy, demo's and status for OptaPlanner 6.1.
:awestruct-layout: normalBase
:awestruct-priority: 1.0
:showtitle:

== OptaPlanner 6.1

We are happy to announce the 6.1 release of OptaPlanner.

OptaPlanner is a lightweight, embeddable planning engine written in Java™
to solve constraint satisfaction problems efficiently. +
Together with the Drools rule engine and the jBPM workflow engine,
it is a strong and flexible foundation for knowledge management.

*link:../../download/download.html#FinalReleases[Download it now]*, link:../../learn/documentation.html#FinalReleases[read the docs]
or link:#NewAndNoteWorthy[scroll to the new and noteworthy].

=== Demo videos

Each of these videos demonstrates an example and a feature:

* http://www.youtube.com/watch?v=u_bl6E7aiNY&list=PLJY69IMbAdq0uKPnjtWXZ2x7KE1eWg3ns[Exam timetabling]: User defined score parametrization
* http://www.youtube.com/watch?v=L98J6HhSCXQ&list=PLJY69IMbAdq0uKPnjtWXZ2x7KE1eWg3ns[Dinner party scheduling]: Decision tables
* http://www.youtube.com/watch?v=K084NKRZqkg&list=PLJY69IMbAdq0uKPnjtWXZ2x7KE1eWg3ns[Cloud optimization]: Decision tables
* http://www.youtube.com/watch?v=xhCtuM-Hiic&list=PLJY69IMbAdq0uKPnjtWXZ2x7KE1eWg3ns[Cloud optimization]: Real time planning
* http://www.youtube.com/watch?v=4meWIhPRVn8&list=PLJY69IMbAdq0uKPnjtWXZ2x7KE1eWg3ns[Course scheduling]: Immovable planning entities
* http://www.youtube.com/watch?v=_2zweB9JD7c&list=PLJY69IMbAdq0uKPnjtWXZ2x7KE1eWg3ns[Project job scheduling]: Build-in hard constraints
* http://www.youtube.com/watch?v=IB2CxfLhHG4&list=PLJY69IMbAdq0uKPnjtWXZ2x7KE1eWg3ns[Tennis club scheduling]: Fairness and load balancing constraints
* http://www.youtube.com/watch?v=BxO3UFmtAPg&list=PLJY69IMbAdq0uKPnjtWXZ2x7KE1eWg3ns[Vehicle routing with time windows]: Shadow variables and real-time planning
* http://www.youtube.com/watch?v=4hp_Qg1hFgE&list=PLJY69IMbAdq0uKPnjtWXZ2x7KE1eWg3ns[Vehicle routing scoring]: Score function flexibility
* http://www.youtube.com/watch?v=7nPagqJK3bs&list=PLJY69IMbAdq0uKPnjtWXZ2x7KE1eWg3ns[Employee rostering]: Continuous planning

=== Status

OptaPlanner is:

* *Stable*: Heavily tested with unit, integration and stress tests.
* *Reliable*: Used across the world. See link:../../learn/testimonialsAndCaseStudies.html[case studies].
* *Scalable*: One of the examples handles `50 000` entities with `5 000` variables each, multiple constraint types and billions of possible constraint matches.
* *Documented*: Read link:../../learn/documentation.html[the detailed reference manual] or one of the many examples.
* *Open source*: Released under link:../../code/license.html[the Apache Software License].

[[NewAndNoteWorthy]]
=== New and noteworthy

==== Public API

There is now a public API:

* Public API: All classes in the package namespace `org.optaplanner.core.api` are 100% backwards compatible in future releases.

* Impl classes: All classes in the package namespace `org.optaplanner.core.impl` are not backwards compatible: they might change in future releases.
The recipe called `UpgradeFromPreviousVersionRecipe.txt` describes every such change and on how to quickly deal with it
when upgrading to a newer version. That recipe file is included in every release zip.

* XML configuration: The XML solver configuration is backwards compatible for all elements,
except for elements that require the use of non public API classes.
The XML solver configuration is defined by the classes in the package namespace `org.optaplanner.core.config`.

==== Performance speedups

* *EntitySelector caching speedup for large datasets*: Benchmarked on MachineReassignment's B datasets.
** Tabu Search: `+3%` on average, `+4%` on largest
** Late Acceptance: `+234%` (`x3.34`) on average, `+430%` (`x5.3`) on largest
* *Generic cloning speedup for large datasets*: Benchmarked on MachineReassignment's B datasets.
** Tabu Search: `+18%` on average, `+24%` on largest
** Late Acceptance: `+23%` on average, `+121%` (`x2.21`) on largest

==== Declarative value ranges

When the planning value range of a planning variable is a number (such as `int`, `double` or `BigDecimal`),
you can now declare the range by its bounds, instead of enumerating all values in the range.

So instead of reserving 5000 memory spaces for all the integer values:

[source,java]
----
    @ValueRangeProvider(id = "delayRange")
    public List<Integer> getDelayRange() {
        List<Integer> = new ArrayList<Integer>(5000);
        for (int i = 0; i < 5000; i++) {
            delayRange.add(i);
        }
        return delayRange;
    }
----

You can now just reserve 2 memory spaces for the bounds of those integer values:

[source,java]
----
    @ValueRangeProvider(id = "delayRange")
    public CountableValueRange<Integer> getDelayRange() {
        return ValueRangeFactory.createIntValueRange(0, 5000);
    }
----

==== New Construction Heuristic: Cheapest Insertion

A new Construction Heuristic that takes considerably longer than First Fit, First Fit Decreasing,
but often has better results.

[source,java]
----
  <constructionHeuristic>
    <constructionHeuristicType>CHEAPEST_INSERTION</constructionHeuristicType>
  </constructionHeuristic>
----

==== New Exhaustive Search: Branch And Bound

Branch And Bound is a smart version of Brute Force.
It also explores nodes in an exponential search tree,
but it investigates more promising nodes first and prunes away worthless nodes.
Configure it like this:

[source,java]
----
  <exhaustiveSearch>
    <exhaustiveSearchType>BRANCH_AND_BOUND</exhaustiveSearchType>
  </exhaustiveSearch>
----

==== BenchmarkAggregator

The BenchmarkAggregator in optaplanner-benchmark allows you to merge multiple benchmark reports into 1 report.

Contributed by Matej Čimbora.

==== Generic move improvements

* New `PillarChangeMove`:
A pillar is a set of planning entities which have the same planning value(s) for their planning variable(s).
The PillarChangeMove selects 1 entity pillar and changes the value of 1 variable for all entities.
* The pillar moves can now select subPillars too.

==== Other improvements

* The Manners2009 example has been cleaned up and renamed to the Dinner Party example.
* *Decision Table* example: the Dinner Party example now demonstrates how to use a Drools Decision Table (an XLS file) to allow users to define score rules.
* New *BestScoreFeasibleTermination*: terminates when the best score is feasible. Contributed by Matej Čimbora.
* Real-time planning improvements, such as a daemon mode.

==== Archive

For older releases, check link:releaseNotesArchive.html[the release notes archive].
