= Release Notes 7.1
:awestruct-description: New and noteworthy, demos and status for OptaPlanner 7.1.
:awestruct-layout: releaseNotesBase
:awestruct-priority: 1.0
:awestruct-release_notes_version: 7.1
:awestruct-release_notes_version_qualifier: Beta

[[NewAndNoteWorthyEngine]]
== New and noteworthy: Engine

=== Construction Heuristic power tweaking made simpler

It's now easier to power tweak the Construction Heuristic's move selectors if desired.
This especially useful to improve scaling for use cases with multiple planning variables.

For example, in course scheduling this will first assign a period to lecture and then a room to a lecture
(instead of the combination of both which is the default behaviour):

[source,xml,options="nowrap"]
----
  <constructionHeuristic>
    <constructionHeuristicType>FIRST_FIT_DECREASING</constructionHeuristicType>
    <changeMoveSelector>
      <valueSelector variableName="period"/>
    </changeMoveSelector>
    <changeMoveSelector>
      <valueSelector variableName="room"/>
    </changeMoveSelector>
  </constructionHeuristic>
----

This means that it will evaluate a lot less moves, resulting in a Construction Heuristic that end much quicker
at the cost of solution quality (which Local Search can usually make up for in the time gained).

[[NewAndNoteWorthyWorkbench]]
== New and noteworthy: Workbench

Nothing yet.


[[NewAndNoteWorthyExecutionServer]]
== New and noteworthy: Execution Server

Nothing yet.
