= Maintenance scheduling and inspection planning
:jbake-type: useCaseBase
:jbake-description: Use OptaPlanner (Java™, open source) to optimize maintenance scheduling, adhering to skill, capacity, SLAs and other constraints.
:jbake-priority: 1.0
:jbake-related_tag: maintenance scheduling
:jbake-featured_youtube_id: dqTrjkVxoPI
:jbake-featured_quickstart_github_url: https://github.com/kiegroup/optaplanner-quickstarts/tree/stable/use-cases/maintenance-scheduling#readme

Machinery and other types of equipment in use (such as elevators, airplanes, trains, roads, railroads, electricity grids, ...)
tend to deteriorate over time, requiring regular maintenance.
Depending on how often each machine requires care,
_maintenance scheduling_ decides when and which skilled engineer visits each machine.
Optimizing this planning problem with a constraint solver AI saves costs
by reducing both too early and too late maintenance,
while adhering to other constraints such as skill requirements, employee availability
and the geographic location of machines.

Inspection planning for bridges, schools, etc., uses a very similar model to maintenance scheduling.

// TODO Maintenance scheduling value proposition image

== What is OptaPlanner?

OptaPlanner is the leading Open Source Java™ AI constraint solver
to optimize maintenance scheduling,
adhering to skill, capacity, SLAs and other constraints.

OptaPlanner is *a lightweight, embeddable planning engine*.
It enables normal Java™ programmers to solve optimization problems efficiently.
It is also compatible with other JVM languages (such as Kotlin and Scala).
Constraints apply on plain domain objects and can call existing code.
There's no need to input constraints as mathematical equations.
Under the hood, OptaPlanner combines sophisticated Artificial Intelligence optimization algorithms
(such as Tabu Search, Simulated Annealing, Late Acceptance and other metaheuristics)
with very efficient score calculation and other state-of-the-art constraint solving techniques.

OptaPlanner is *open source software*, released under link:../../code/license.html[the Apache License].
It is written in 100% pure Java™, runs on any JVM and is available in link:../../download/download.html[the Maven Central repository] too.
