= Testimonials and Case Studies
:awestruct-layout: base
:showtitle:

OptaPlanner is used all over the world to optimize all kinds of planning problems.
Some our users have shared their story:

== Case Studies

* link:caseStudies/OptaPlannerCaseStudy_RJV_2013-06-14.pdf[Task assignment] for RJV (Belgium)

== Articles

* http://www.viaboxxsystems.de/vehicle-routing-optaplanner[Vehicle routing with real routes]
and http://www.viaboxxsystems.de/scaling-vehicle-routing-problem[scaling it] (Germany)

* http://java.dzone.com/articles/drools-planner-billboard[Billboard advertisement scheduling] for EPAMEDIA (Austria)

== Testimonials

* OptaPlanner rocks! Complex planning problems solving & optimization made easy. We love it! - https://twitter.com/veggen/status/185712254036094976[Vincent Eggen]

* Thanks to OptaPlanner we are able to provide fast and affordable automated resource planning cloud service to IT organisations in Germany. - Reinis Vicups

* Speedyroute.com changed from OpenOpt to OptaPlanner to provide optimised delivery routes - https://twitter.com/magic_hat_ltd/status/460154384463441923[Magic Hat Solutions]

* Using OptaPlanner for the first time, I was able to build a proof-of-concept for a complex scheduling and packing problem in less than 2 days. - Jannes Verstichel

== Share your story

If you would like share a case study, article or 1-line testimonial, link:../community/socialMedia.html[let us know]:
we might add it here and share it on the social media.
