= 制約充足ソルバー（Java™、オープンソース）
:jbake-type: localizedBase
:jbake-description: OptaPlannerは100％Javaで書かれた、軽量、組み込み可能な、オープンソースの計画エンジンです。
:jbake-lang: ja
:jbake-priority: 1.0
:showtitle:

== OptaPlannerとは何ですか？

OptaPlannerは**制約充足ソルバー**です。ビジネス・リソース・プランニングを最適化します。すべての組織は、スケジューリングパズルに直面しています：お客様へ製品やサービスを提供するために、限りある、そして、*制約のかかった*リソース（従業員、設備、時間とお金）を割り当てます。 OptaPlannerは、そのような計画の問題を最適化し、**より少ないリソースでより多くのビジネスを行う**ことを助けます。ユースケースは、link:../../learn/useCases/vehicleRoutingProblem.html[配車計画]、勤務表作成、ジョブスケジューリング、ビンパッキング、その他多くを含みます。

OptaPlannerは、**軽量、組み込み可能な計画エンジン**です。通常のJava™プログラマが、効率的に最適化問題を解くことを可能にします。制約は、プレーンなドメインオブジェクトに適用され、既存のコードを再利用することができます。難しい数学の方程式の入力は必要ありません。OptaPlannerは内部に高度な最適化ヒューリスティックとメタヒューリスティック（例えばタブサーチ、シミュレーテッドアニーリング（焼きなまし法）とレイトアクセプタンス）、そして、非常に効率的なスコア計算を兼ね備えています。

OptaPlannerは、link:../../code/license.html[Apache License]の下でリリースしている**オープンソースソフトウェア**です。100％ pure Java™で記述され、任意のJVM上で実行され、link:../../download/download.html[Mavenのセントラルリポジトリ]からも入手可能です。

== 記事

* http://jp-redhat.com/openeye_online/column/middleware-channel/3793/[「ビジネスリソースプランナー」のご紹介：『シフト管理デモ』を使ってみよう]

* http://www.scsk.jp/news/2016/press/product/20160418.html[Red Hat JBoss BRMSの新機能Business Resource Plannerを利用した]

* http://www.ogis-ri.co.jp/otc/hiroba/technical/optaplanner[OptaPlannerによる組み合わせ最適化]

* http://d.hatena.ne.jp/tokobayashi/searchdiary?word=%5BOptaPlanner%5D[tokobayashiの日記]

== 勉強会

* https://groups.google.com/forum/#!forum/optaplanner-study-jp[OptaPlanner 勉強会]
