= Release Notes 6.1
:jbake-type: releaseNotesBase
:jbake-description: New and noteworthy, demos and status for OptaPlanner 6.1.
:jbake-priority: 1.0
:jbake-release_notes_version: 6.1
:jbake-release_notes_version_qualifier: Final

[[NewAndNoteWorthy]]
== New and noteworthy

=== Public API

There is now a public API:

* Public API: All classes in the package namespace `org.optaplanner.core.api` are 100% backwards compatible in future releases.

* Impl classes: All classes in the package namespace `org.optaplanner.core.impl` are not backwards compatible: they might change in future releases.
The recipe called `UpgradeFromPreviousVersionRecipe.txt` describes every such change and on how to quickly deal with it
when upgrading to a newer version. That recipe file is included in every release zip.

* XML configuration: The XML solver configuration is backwards compatible for all elements,
except for elements that require the use of non-public API classes.
The XML solver configuration is defined by the classes in the package namespace `org.optaplanner.core.config`.

=== Performance speedups

* *EntitySelector caching speedup for large datasets*: Benchmarked on MachineReassignment's B datasets.
** Tabu Search: `+3%` on average, `+4%` on largest
** Late Acceptance: `+234%` (`x3.34`) on average, `+430%` (`x5.3`) on largest
* *Generic cloning speedup for large datasets*: Benchmarked on MachineReassignment's B datasets.
** Tabu Search: `+18%` on average, `+24%` on largest
** Late Acceptance: `+23%` on average, `+121%` (`x2.21`) on largest

=== Declarative value ranges

When the planning value range of a planning variable is a number (such as `int`, `double` or `BigDecimal`),
you can now declare the range by its bounds, instead of enumerating all values in the range.

So instead of reserving 5000 memory spaces for all the integer values:

[source,java]
----
    @ValueRangeProvider(id = "delayRange")
    public List<Integer> getDelayRange() {
        List<Integer> = new ArrayList<Integer>(5000);
        for (int i = 0; i < 5000; i++) {
            delayRange.add(i);
        }
        return delayRange;
    }
----

You can now just reserve 2 memory spaces for the bounds of those integer values:

[source,java]
----
    @ValueRangeProvider(id = "delayRange")
    public CountableValueRange<Integer> getDelayRange() {
        return ValueRangeFactory.createIntValueRange(0, 5000);
    }
----

=== New Construction Heuristic: Cheapest Insertion

A new Construction Heuristic that takes considerably longer than First Fit, First Fit Decreasing,
but often has better results.

[source,xml]
----
  <constructionHeuristic>
    <constructionHeuristicType>CHEAPEST_INSERTION</constructionHeuristicType>
  </constructionHeuristic>
----

=== New Exhaustive Search: Branch And Bound

Branch And Bound is a smart version of Brute Force.
It also explores nodes in an exponential search tree,
but it investigates more promising nodes first and prunes away worthless nodes.
Configure it like this:

[source,xml]
----
  <exhaustiveSearch>
    <exhaustiveSearchType>BRANCH_AND_BOUND</exhaustiveSearchType>
  </exhaustiveSearch>
----

=== BenchmarkAggregator

The BenchmarkAggregator in optaplanner-benchmark allows you to merge multiple benchmark reports into 1 report.

Contributed by Matej Čimbora.

=== Generic move improvements

* New `PillarChangeMove`:
A pillar is a set of planning entities which have the same planning value(s) for their planning variable(s).
The PillarChangeMove selects 1 entity pillar and changes the value of 1 variable for all entities.
* The pillar moves can now select subPillars too.

=== Other improvements

* The Manners2009 example has been cleaned up and renamed to the Dinner Party example.
* *Decision Table* example: the Dinner Party example now demonstrates how to use a Drools Decision Table (an XLS file) to allow users to define score rules.
* New *BestScoreFeasibleTermination*: terminates when the best score is feasible. Contributed by Matej Čimbora.
* Real-time planning improvements, such as a daemon mode.
