= Forum
:awestruct-description: Community support and developer mailing list.
:awestruct-layout: normalBase
:showtitle:

== Usage questions

If you have a question about OptaPlanner, just ask our friendly volunteer community:

* *http://stackoverflow.com/questions/tagged/optaplanner[Ask a technical usage question on StackOverflow.]*

* To start an opinionated discussion, use https://groups.google.com/forum/#!forum/optaplanner-dev[the OptaPlanner developer forum] instead.
Do not cross post to both channels.

Community support is privilege, not a right. Please *follow these recommendations* when posting a question or a discussion
to increase your chance to get a helpful answer:

* Get to the point. Keep it as short as possible.
* Include _relevant_ technical details (stacktrace, short code snippet, configuration snippet, ...).
* Be polite, friendly and clear. Reread your question before posting it.
* Be patient. This isn't link:product.html[paid support]. There is no SLA.
* Do not email or tweet developers directly for support, unless you 've got link:product.html[a paid support subscription].

Our developers are active in the volunteer community.

== Development discussions

If you've link:../code/sourceCode.html[build OptaPlanner from source] and want to improve something, come talk with us:

* Join https://groups.google.com/forum/#!forum/optaplanner-dev[the OptaPlanner developer google group].

** Mail directly to the group via mailto:optaplanner-dev@googlegroups.com[optaplanner-dev@googlegroups.com].

* And link:chat.html[chat with us] (recommended).

== Enterprise support

If you 've got link:product.html[a Red Hat support subscription],
then https://access.redhat.com[open a support case] to get priority support.
