= Upgrade recipe 8
:awestruct-description: Upgrade to OptaPlanner 8 from a previous version.
:awestruct-layout: upgradeRecipeBase
:awestruct-priority: 0.5
:awestruct-upgrade_recipe_version: 8


// TODO Once 8.0.0.Beta1 is out, remove these lines and add a link to this page in ./index.adoc
*OptaPlanner 8 is in _alpha_ development.
There is no use in waiting for it.
Please use and download the latest 7.x release instead.*

== From 7.39.0.Final to 8.0.0.Beta1

=== Backwards incompatible changes to the public API in 7.0

Because this is a new major version number (8.0), which is the foundation for the 8.x series for the next few years,
it allows us to make backwards incompatible changes to the public API _for the long term benefit of this project_.

We kept these backwards incompatible changes to a strict minimum
and will not introduce any additional ones during the 8.x era.

Any backwards incompatible changes are annotated with a [.label.label-danger.label-as-badge.label-public-api]#Public API# badge.


[.upgrade-recipe-major.upgrade-recipe-public-api]
=== Java 11 or higher required

If you're using JRE or JDK 8, upgrade to JDK 11 or higher.

JDK 11 or higher is still available for _free_ (including security and bug fixes),
alongside Oracle's paid subscription.

* On linux, get OpenJDK from your linux software repository.
For example on Fedora and RHEL:
+
[source, bash]
----
sudo dnf install java-11-openjdk-devel
----

* On Windows and Mac, https://adoptopenjdk.net[download OpenJDK from AdoptOpenJDK].

We currently intend to support a minimal version of Java 11 throughout the entire 8.x series.


[.upgrade-recipe-major.upgrade-recipe-public-api]
=== OSGi metadata removed

Due to the limited usage of OSGi and the maintenance burden it brings,
the OptaPlanner jars in the 8.x series no longer include OSGi metadata in their `META-INF/MANIFEST.MF` file.


