= Upgrade recipe 7.0
:awestruct-description: Upgrade to OptaPlanner 7.0 from a previous version.
:awestruct-layout: upgradeRecipeBase
:awestruct-priority: 0.5
:awestruct-upgrade_recipe_version: 7.0

== Backwards incompatible changes to the public API

Because this is a new major version number (7.0), which is the foundation for the 7.x series for the next few years,
it allows us to make backwards incompatible changes to the public API _for the long term benefit of this project_.

Our current intention is to keep these backwards incompatible changes to a strict minimum
(by favoring deprecation over removal) and do not introduce any additional ones after 7.0.

Any backwards incompatible changes are annotated with a [.label.label-danger.label-as-badge.label-public-api]#Public API# badge.


== From 6.4.0.Final to 7.0.0.Beta1


[.upgrade-recipe-major.upgrade-recipe-public-api]
=== Java 8 or higher required

If you're using JRE or JDK 6 or 7, upgrade to JDK 8 or higher.

We currently intend to support a minimal version of Java 8 throughout the entire 7.x series.


[.upgrade-recipe-minor.upgrade-recipe-public-api]
===  Deprecated methods removed

The following long term deprecated methods have been finally removed:

* Setters on `ScoreHolder` implementations, such as `HardSoftScoreHolder.setHardScore(int)` and `setSoftScore(int)`.
Use `addHardConstraintMatch(...)` and `addSoftConstraintMatch(...)` in your score rules instead.
See link:./upgradeRecipe6.0.html[this upgrade recipe].

* The experimental, deprecated, hybrid metaheuristic called `LATE_SIMULATED_ANNEALING`
(which was inspired by both Late Acceptance and Simulated Annealing) has been removed.

* The dead, deprecated code of `DeciderScoreComparatorFactory` has been removed.
See link:./upgradeRecipe6.2.html[this upgrade recipe].

* The deprecated `SolverBenchmarkBluePrintType.ALL_CONSTRUCTION_HEURISTIC_TYPES` has been removed.
See link:./upgradeRecipe6.3.html[this upgrade recipe].


[.upgrade-recipe-major]
=== `Solution` interface removed (deprecated)

Your solution class no longer needs to have both the `@PlanningSolution` annotation and implement the `Solution` interface,
only the annotation suffices. The `Solution` interface has been deprecated and will be removed in a future version.

Remove the `Solution` interface, annotate the `getScore()` method with `@PlanningScore`
and replace the `getProblemFacts()` method with a `@ProblemFactCollectionProperty` annotation directly on every problem fact getter (or field).

Before in `*.java`:
[source, java]
----
@PlanningSolution
public class CloudBalance implements Solution<HardSoftScore> {

    private List<CloudComputer> computerList;
    ...

    private HardSoftScore score;

    @ValueRangeProvider(id = "computerRange")
    public List<CloudComputer> getComputerList() {...}

    public HardSoftScore getScore() {...}
    public void setScore(HardSoftScore score) {...}

    public Collection<? extends Object> getProblemFacts() {
        List<Object> facts = new ArrayList<Object>();
        facts.addAll(computerList);
        ...
        return facts;
    }

}
----

After in `*.java`:
[source, java]
----
@PlanningSolution
public class CloudBalance {

    private List<CloudComputer> computerList;
    ...

    private HardSoftScore score;

    @ValueRangeProvider(id = "computerRange")
    @ProblemFactCollectionProperty
    public List<CloudComputer> getComputerList() {...}

    @PlanningScore
    public HardSoftScore getScore() {...}
    public void setScore(HardSoftScore score) {...}

}
----

For a single problem fact (which is not wrapped in a `Collection`), use the `@ProblemFactProperty` annotation,
as shown below (with field annotations this time).

Before in `*.java`:
[source, java]
----
@PlanningSolution
public class CloudBalance implements Solution<HardSoftScore> {

    private CloudParametrization parametrization;
    private List<CloudBuilding> buildingList;
    @ValueRangeProvider(id = "computerRange")
    private List<CloudComputer> computerList;
    ...

    public Collection<? extends Object> getProblemFacts() {
        List<Object> facts = new ArrayList<Object>();
        facts.add(parametrization); // not a Collection
        facts.addAll(buildingList);
        facts.addAll(computerList);
        ...
        return facts;
    }

}
----

After in `*.java`:
[source, java]
----
@PlanningSolution
public class CloudBalance {

    @ProblemFactProperty
    private CloudParametrization parametrization;
    @ProblemFactCollectionProperty
    private List<CloudBuilding> buildingList;
    @ValueRangeProvider(id = "computerRange")
    @ProblemFactCollectionProperty
    private List<CloudComputer> computerList;
    ...

}
----

Don't add the `@ProblemFactCollectionProperty` annotation on getters (or fields)
that have a `@PlanningEntityCollectionProperty` annotation.


[.upgrade-recipe-minor.upgrade-recipe-public-api]
===  `Solver`: return values no longer implement `Solution`

Because the `Solution` interface was deprecated (see the section below to upgrade from 6.4.0.Final to 7.0.0.Beta1),
the `Solver.solve(...)` and `Solver.getBestSolution()` methods now return an `Object` instead of a `Solution` instance
(if and only if no type parameter is specified for the `Solver`).

*This only applies if you're still using a `Solver` without a type parameter
and if you're not casting the return value immediately to your solution implementation (which is unlikely).*

Before in `*.java`:
[source, java]
----
Solution s = solver.solve(problem);
CloudBalance solution = (CloudBalance) s;
----

After in `*.java` (quick and dirty fix):
[source, java]
----
CloudBalance solution = (CloudBalance) solver.solve(problem);
----

After in `*.java` (recommended fix):
[source, java]
----
SolverFactory<CloudBalance> factory = SolverFactory.createFromXmlResource(...);
Solver<CloudBalance> solver = factory.buildSolver();
...
CloudBalance solution = solver.solve(problem);
----


[.upgrade-recipe-minor.upgrade-recipe-public-api]
===  `BestSolutionChangedEvent.getNewBestSolution()`: return value no longer implement `Solution`

Because the `Solution` interface was deprecated (see the section below to upgrade from 6.4.0.Final to 7.0.0.Beta1),
the `BestSolutionChangedEvent.getNewBestSolution()` method now returns an `Object`
(if and only if no type parameter is specified for the `SolverEventListener`).

*This only applies if you're still using a `SolverEventListener` without a type parameter
and if you're not casting the return value immediately to your solution implementation (which is unlikely).*

Before in `*.java`:
[source, java]
----
SolverFactory factory = SolverFactory.createFromXmlResource(...);
Solver solver = factory.buildSolver();
solver.addEventListener(new SolverEventListener() {
    @Override
    public void bestSolutionChanged(BestSolutionChangedEvent event) {
        Solution s = event.getNewBestSolution();
        CloudBalance solution = (CloudBalance) s;
        ...
    }
});
----

After in `*.java`:
[source, java]
----
SolverFactory<CloudBalance> factory = SolverFactory.createFromXmlResource(...);
Solver<CloudBalance> solver = factory.buildSolver();
solver.addEventListener(new SolverEventListener<CloudBalance>() {
    @Override
    public void bestSolutionChanged(BestSolutionChangedEvent<CloudBalance> event) {
        CloudBalance solution = event.getNewBestSolution();
        ...
    }
});
----

And you'll probably want to use a lamdba here:

[source, java]
----
SolverFactory<CloudBalance> factory = SolverFactory.createFromXmlResource(...);
Solver<CloudBalance> solver = factory.buildSolver();
solver.addEventListener(event -> {
    CloudBalance solution = event.getNewBestSolution();
    ...
});
----


[.upgrade-recipe-major]
=== `SolutionFileIO`: added optional generic type parameter

To avoid the awkward cast to your `Solution` implementation and to get rid of that deprecated interface,
`SolutionFileIO` now optionally supports a generic type parameter (which is the solution class).

Before in `*.java`:
[source, java]
----
public class TspFileIO implements SolutionFileIO {
    ...

    public Solution read(File inputSolutionFile) {...}

    public void write(Solution solution, File outputSolutionFile) {
        TspSolution tspSolution = (TspSolution) solution;
        ...
    }

}
----

After in `*.java`:
[source, java]
----
public class TspFileIO implements SolutionFileIO<TspSolution> {
    ...

    public TspSolution read(File inputSolutionFile) {...}

    public void write(TspSolution tspSolution, File outputSolutionFile) {
        ...
    }

}
----


[.upgrade-recipe-minor]
=== `XStreamSolutionFileIO`: added optional generic type parameter

To avoid the awkward cast to your `Solution` implementation and to get rid of that deprecated interface,
`XStreamSolutionFileIO` now optionally supports a generic type parameter (which is the solution class).

Before in `*.java`:
[source, java]
----
SolutionFileIO solutionFileIO = new XStreamSolutionFileIO(CloudBalance.class);
----

After in `*.java`:
[source, java]
----
SolutionFileIO<CloudBalance> solutionFileIO = new XStreamSolutionFileIO<>(CloudBalance.class);
----


[.upgrade-recipe-minor]
=== `CustomPhaseCommand`: added optional generic type parameter

To avoid the awkward cast to your `Solution` implementation and to get rid of that deprecated interface,
`CustomPhaseCommand` now optionally supports a generic type parameter (which is the solution class).

Before in `*.java`:
[source, java]
----
public class DinnerPartySolutionInitializer extends AbstractCustomPhaseCommand {

    public void changeWorkingSolution(ScoreDirector scoreDirector) {
        DinnerParty dinnerParty = (DinnerParty) scoreDirector.getWorkingSolution();
        ...
    }

}
----

After in `*.java`:
[source, java]
----
public class DinnerPartySolutionInitializer extends AbstractCustomPhaseCommand<DinnerParty> {

    public void changeWorkingSolution(ScoreDirector<DinnerParty> scoreDirector) {
        DinnerParty dinnerParty = scoreDirector.getWorkingSolution();
        ...
    }

}
----


[.upgrade-recipe-major]
=== `ProblemFactChange`: added optional generic type parameter

To avoid the awkward cast to your `Solution` implementation and to get rid of that deprecated interface,
`ProblemFactChange` now optionally supports a generic type parameter (which is the solution class).

Before in `*.java`:
[source, java]
----
        solver.addProblemFactChange(new ProblemFactChange() {
            public void doChange(ScoreDirector scoreDirector) {
                CloudBalance cloudBalance = (CloudBalance) scoreDirector.getWorkingSolution();
                ...
            }
        });
----

After in `*.java`:
[source, java]
----
        solver.addProblemFactChange(new ProblemFactChange<CloudBalance>() {
            public void doChange(ScoreDirector<CloudBalance> scoreDirector) {
                CloudBalance cloudBalance = scoreDirector.getWorkingSolution();
                ...
            }
        });
----

After in `*.java` (with lamdba):
[source, java]
----
        solver.addProblemFactChange(scoreDirector -> {
            CloudBalance cloudBalance = scoreDirector.getWorkingSolution();
            ...
        });
----


[.upgrade-recipe-minor]
=== `Bendable*Score`: `toString()` changed

A bendable score (`BendableScore`, `BendableLongScore` or `BendableBigDecimalScore`) 's `String`
has changed so it can be parsed without the ScoreDefinition

Before in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
      <termination>
        <bestScoreLimit>0/0/-1/-2/-3</bestScoreLimit>
      </termination>
----

After in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
      <termination>
        <bestScoreLimit>[0/0]hard/[-1/-2/-3]soft</bestScoreLimit>
      </termination>
----

Before in XStream `*.xml` output with `optaplanner-persistence-xstream`:
[source, xml]
----
      <score>0/0/-1/-2/-3</score>
----

After in in XStream `*.xml` output with `optaplanner-persistence-xstream`:
[source, xml]
----
      <score>[0/0]hard/[-1/-2/-3]soft</score>
----


[.upgrade-recipe-major]
=== `EnvironmentMode`: `PRODUCTION` renamed

The `EnvironmentMode` `PRODUCTION` has been renamed to `NON_REPRODUCIBLE`
because most enterprises use `REPRODUCIBLE` in production and that's fine.
For backwards compatibility, `PRODUCTION` still exists, but it's deprecated and it will be removed in a future version.

Before in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
<solver>
  <environmentMode>PRODUCTION</environmentMode>
  ...
</solver>
----

After in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
<solver>
  <environmentMode>NON_REPRODUCIBLE</environmentMode>
  ...
</solver>
----


[.upgrade-recipe-readme]
=== Average calculate count renamed to score calculation speed

In the logs and the benchmark report, the _average calculate count per second_ has been renamed to _score calculation speed_.


[.upgrade-recipe-minor]
=== `Termination`: `calculateCountLimit` renamed

The termination configuration property `calculateCountLimit` has been renamed to `scoreCalculationCountLimit`.
The property `calculateCountLimit`  has been deprecated and will be removed in a future version.

Before in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
  <termination>
    <calculateCountLimit>100000</calculateCountLimit>
  </termination>
----

After in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
  <termination>
    <scoreCalculationCountLimit>100000</scoreCalculationCountLimit>
  </termination>
----


[.upgrade-recipe-minor]
=== `ProblemStatisticType`: `CALCULATE_COUNT_PER_SECOND` renamed

The benchmark ProblemStatisticType `SCORE_CALCULATION_SPEED` has been renamed to `SCORE_CALCULATION_SPEED`.

Before in `*BenchmarkConfig.xml`:
[source, xml]
----
      <problemStatisticType>CALCULATE_COUNT_PER_SECOND</problemStatisticType>
----

After in `*BenchmarkConfig.xml`:
[source, xml]
----
      <problemStatisticType>SCORE_CALCULATION_SPEED</problemStatisticType>
----


[.upgrade-recipe-readme]
=== `Score`: uninitialized variable count

A solution's `Score` now also contains the number of uninitialized variables (usually `0`) as a negative `getInitScore()`.
This is useful in exotic cases with multiple phases to fully initialize a solution.
It also prevents bugs in multi-threaded use cases.

With `Score.isSolutionInitialized()`, it's now possible to quickly and reliably determine if a solution is fully initialized.
The method `FeasibleScore.isFeasible()` now also checks if the solution was fully initialized during score calculation.


[.upgrade-recipe-major]
=== `EasyScoreCalculator`: `calculateScore()` changed

The `EasyScoreCalculator` interface method `calculateScore(solution)` has been changed to `calculateScore(solution, initScore)`.
Change the method signature to add the `initScore` and then pass it to the `Score.valueOf()` method.

Before in `*.java`:
[source, java]
----
public class CloudBalancingEasyScoreCalculator implements EasyScoreCalculator<CloudBalance> {

    public HardSoftScore calculateScore(CloudBalance cloudBalance) {
        ...
        return HardSoftScore.valueOf(hardScore, softScore);
    }

}
----

After in `*.java`:
[source, java]
----
public class CloudBalancingEasyScoreCalculator implements EasyScoreCalculator<CloudBalance> {

    public HardSoftScore calculateScore(CloudBalance cloudBalance, int initScore) {
        ...
        return HardSoftScore.valueOf(initScore, hardScore, softScore);
    }

}
----

OptaPlanner keeps track of the `initScore` internally, but it needs to be passed into the `Score` creation because a `Score` is immutable by design.


[.upgrade-recipe-minor]
=== `IncrementalScoreCalculator`: `calculateScore()` changed

The `IncrementalScoreCalculator` interface method `calculateScore()` has been changed to `calculateScore(initScore)`.
Change the method signature to add the `initScore` and then pass it to the `Score.valueOf()` method.

Before in `*.java`:
[source, java]
----
public class CloudBalancingIncrementalScoreCalculator extends AbstractIncrementalScoreCalculator<CloudBalance> {

    public HardSoftScore calculateScore() {
        return HardSoftScore.valueOf(hardScore, softScore);
    }

}
----

After in `*.java`:
[source, java]
----
public class CloudBalancingIncrementalScoreCalculator extends AbstractIncrementalScoreCalculator<CloudBalance> {

    public HardSoftScore calculateScore(int initScore) {
        return HardSoftScore.valueOf(initScore, hardScore, softScore);
    }

}
----


[.upgrade-recipe-major.upgrade-recipe-public-api]
=== `Score`: `valueOf(...)` changed and `valueOfInitialized(...)` added

Each `Score` implementation now requires an `initScore` parameter.
Inside a `ScoreCalculator`, the `initScore` must be passed from the `calculateScore()` method (see the 2 previous notes above).

Outside of a `ScoreCalculator`, if you're constructing a score for an initialized solution,
just replace `valueOf()` with `valueOfInitialized()`:

Before in `*.java`:
[source, java]
----
        SimpleScore score = SimpleScore.valueOf(1234);
----

After in `*.java`:
[source, java]
----
        SimpleScore score = SimpleScore.valueOfInitialized(1234);
----

Or with a `HardSoftScore`:

Before in `*.java`:
[source, java]
----
        HardSoftScore score = HardSoftScore.valueOf(1200, 34);
----

After in `*.java`:
[source, java]
----
        HardSoftScore score = HardSoftScore.valueOfInitialized(1200, 34);
----

It is intentional that `valueOfInitialized()` doesn't just overload `valueOf()`,
to avoid that an `EasyScoreCalculator` implementation forgets to pass the `initScore` parameter.


[.upgrade-recipe-major]
=== `BestSolutionChangedEvent`: `isNewBestSolutionInitialized()` replaced

The method `BestSolutionChangedEvent.isNewBestSolutionInitialized()`
has been deprecated in favor of `BestSolutionChangedEvent.getNewBestSolution().getScore().isSolutionInitialized()`.

Before in `*.java`:
[source, java]
----
    public void bestSolutionChanged(BestSolutionChangedEvent<CloudBalance> event) {
        if (event.isEveryProblemFactChangeProcessed()
                && event.isNewBestSolutionInitialized()) {
            ...
        }
    }
----

After in `*.java`:
[source, java]
----
    public void bestSolutionChanged(BestSolutionChangedEvent<CloudBalance> event) {
        if (event.isEveryProblemFactChangeProcessed()
                && event.getNewBestSolution().getScore().isSolutionInitialized()) {
            ...
        }
    }
----

However, if you also check `isFeasible()`, that's enough because it now also checks if the solution is initialized.

After in `*.java` for a `FeasibleScore`:
[source, java]
----
    public void bestSolutionChanged(BestSolutionChangedEvent<CloudBalance> event) {
        if (event.isEveryProblemFactChangeProcessed()
                // isFeasible() checks isSolutionInitialized() too
                && event.getNewBestSolution().getScore().isFeasible()) {
            ...
        }
    }
----


[.upgrade-recipe-minor]
=== Custom initializer: `Score.compareTo()` behaviour changed

The `Score.compareTo()` now also takes the uninitialized variable count into account.
If you have a `CustomPhaseCommand` that implements a custom solution initializer (instead of using a Construction Heuristic),
it will need to transform all scores with `Score.toInitializedScore()` before comparison to avoid making the wrong decision:

Before in `*.java`:
[source, java]
----
public class DinnerPartySolutionInitializer extends AbstractCustomPhaseCommand<DinnerParty> {
    ...

    private void initializeSeatDesignationList(ScoreDirector<DinnerParty> scoreDirector, DinnerParty dinnerParty) {
        ...
        for (SeatDesignation seatDesignation : dinnerParty.getSeatDesignationList()) {
            Score bestScore = SimpleScore.valueOf(Integer.MIN_VALUE);
            ...
            for (Seat seat : undesignatedSeatList) {
                ...
                if (score.compareTo(bestScore) > 0) {
                    bestScore = score;
                    ...
                }
            }
            ...
        }
    }

}
----

After in `*.java`:
[source, java]
----
public class DinnerPartySolutionInitializer extends AbstractCustomPhaseCommand<DinnerParty> {
    ...

    private void initializeSeatDesignationList(ScoreDirector<DinnerParty> scoreDirector, DinnerParty dinnerParty) {
        ...
        for (SeatDesignation seatDesignation : dinnerParty.getSeatDesignationList()) {
            Score bestScore = SimpleScore.valueOfInitialized(Integer.MIN_VALUE);
            ...
            for (Seat seat : undesignatedSeatList) {
                ...
                if (score.toInitializedScore().compareTo(bestScore.toInitializedScore()) > 0) {
                    bestScore = score;
                    ...
                }
            }
            ...
        }
    }

}
----


[.upgrade-recipe-minor]
=== `Score` and `ScoreDefinition`: methods changed

The `ScoreDefinition.fromLevelNumbers(...)` method now requires an `initScore` parameter.

Before in `*.java`:
[source, java]
----
Score score = scoreDefinition.fromLevelNumbers(new int[]{0, -200});
----

After in `*.java` (quick and dirty fix):
[source, java]
----
Score score = scoreDefinition.fromLevelNumbers(0, new int[]{0, -200});
----


[.upgrade-recipe-minor]
=== Custom `Score`: methods added

If you have a custom `Score`:
The `Score` interface has several new methods: `getInitScore()`, `isSolutionInitialized()` and `toInitializedScore()`.
The first two methods are implemented by `AbstractScore`, but the last method needs to be specifically implemented.

Before in `*.java`:
[source, java]
----
public final class HardSoftScore extends AbstractScore<HardSoftScore> ... {
    ...
}
----

After in `*.java`:
[source, java]
----
public final class HardSoftScore extends AbstractScore<HardSoftScore> ... {
    ...

    public HardSoftScore toInitializedScore() {
        return initScore == 0 ? this : new HardSoftScore(0, hardScore, softScore);
    }

}
----

Furthermore, a score that implements `FeasibleScore` needs to take the `initScore` into account in the `isFeasible()` method implementation.


[.upgrade-recipe-minor]
=== Hibernate integration: extra `@Column` needed

Because a `Score` now also contains an `initScore` of type `int` (regardless of the type of the other fields),
add an extra `@Column` annotation to the beginning of the `@Columns` list to map that field to a database column.

Set it to `0` for all existing records (unless you have reason to believe that some scores weren't calculated on a fully initialized solution).

Before in `*.java`:
[source, java]
----
        @Columns(columns = {
                @Column(name = "hardScore"),
                @Column(name = "softScore")})
        public HardSoftScore getScore() {
            return score;
        }
----

After in `*.java`:
[source, java]
----
        @Columns(columns = {
                @Column(name = "initScore"),
                @Column(name = "hardScore"),
                @Column(name = "softScore")})
        public HardSoftScore getScore() {
            return score;
        }
----


[.upgrade-recipe-impl-detail]
=== `XStreamSolutionFileIO`: no-arg constructor removed

The no-arg constructor of `XStreamSolutionFileIO` has been removed because it's useless.


[.upgrade-recipe-minor]
=== JAXB support added

If you're using JAXB, take advantage the new JAXB Score bindings etc.
See the reference manual, chapter _Integration_.

These new `ScoreJaxbXmlAdapter` implementations have been promoted to the public API,
so they are guaranteed to be backwards compatible in future versions.


[.upgrade-recipe-minor]
=== Jackson support added

If you're using Jackson, take advantage the new Jackson Score bindings etc.
See the reference manual, chapter _Integration_.

These new `ScoreJacksonJsonSerializer` and `ScoreJacksonJsonDeserializer` implementations have been promoted to the public API,
so they are guaranteed to be backwards compatible in future versions.


[.upgrade-recipe-major]
=== `XStreamScoreConverter` replaced

The general purpose `XStreamScoreConverter` to bind `Score` implementations
has been replaced by specific implementations, such as `HardSoftScoreXStreamConverter` and `SimpleScoreXStreamConverter`
that are easier to use.

Furthermore, these  new `ScoreXStreamConverter` implementations have been promoted to the public API,
so they are now guaranteed to be backwards compatible in future versions.

Before in `*.java`:
[source, java]
----
public class CloudBalance {

    @XStreamConverter(value = XStreamScoreConverter.class, types = {HardSoftScoreDefinition.class})
    private HardSoftScore score;

    ...
}
----

After in `*.java`:
[source, java]
----
public class CloudBalance {

    @XStreamConverter(HardSoftScoreXStreamConverter.class)
    private HardSoftScore score;

    ...
}
----

For a bendable score, it's no longer needed to configure the `hardLevelSize` and `softLevelSize`.

Before in `*.java`:
[source, java]
----
public class Schedule {

    @XStreamConverter(value = XStreamScoreConverter.class, types = {BendableScoreDefinition.class}, ints = {1, 2})
    private BendableScore score;

    ...
}
----

After in `*.java`:
[source, java]
----
public class Schedule {

    @XStreamConverter(BendableScoreXStreamConverter.class)
    private BendableScore score;

    ...
}
----


[.upgrade-recipe-major.upgrade-recipe-public-api]
===  `@CustomShadowVariable`: `sources` type changed

A shadow variable annotated with `@CustomShadowVariable`
now expects that the `sources` parameter to is of type `@PlanningVariableReference`
instead of `@CustomShadowVariable.Source`.

This way it's consistent with the `variableListenerRef` parameter.

Before in `*.java`:
[source, java]
----
        @CustomShadowVariable(variableListenerClass = ArrivalTimeUpdatingVariableListener.class,
                sources = {@CustomShadowVariable.Source(variableName = "previousStandstill")})
        public Long getArrivalTime() {
            return arrivalTime;
        }
----

After in `*.java`:
[source, java]
----
        @CustomShadowVariable(variableListenerClass = ArrivalTimeUpdatingVariableListener.class,
                sources = {@PlanningVariableReference(variableName = "previousStandstill")})
        public Long getArrivalTime() {
            return arrivalTime;
        }
----


== From 7.0.0.Beta1 to 7.0.0.Beta2


[.upgrade-recipe-minor]
===  `ProblemFactChange`: `before/afterProblemFactChanged` renamed

The `ScoreDirector` methods `beforeProblemFactChanged()` and `afterProblemFactChanged()`
have been renamed to `beforeProblemPropertyChanged()` and `afterProblemPropertyChanged()`.
This can affect your `ProblemFactChange` implementations.

A problem fact is a class that doesn't change during planning.
A problem property is a property on a problem fact or a planning entity that doesn't change during planning
(so it's not a planning variable).

Before in `*.java`:
[source, java]
----
        scoreDirector.beforeProblemFactChanged(computer);
        computer.setMemory(newMemoryCapacity);
        scoreDirector.afterProblemFactChanged(computer);
----

After in `*.java`:
[source, java]
----
        scoreDirector.beforeProblemPropertyChanged(computer);
        computer.setMemory(newMemoryCapacity);
        scoreDirector.afterProblemPropertyChanged(computer);
----


[.upgrade-recipe-major]
=== Solver configuration: `<scoreDefinitionType>` removed

Don't specify the `scoreDefinitionType` in the solver configuration any more
because OptaPlanner will now figure out it automatically from the domain.

Before in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
  <scoreDirectorFactory>
    <scoreDefinitionType>HARD_SOFT</scoreDefinitionType>
    <scoreDrl>org/optaplanner/examples/cloudbalancing/solver/cloudBalancingScoreRules.drl</scoreDrl>
  </scoreDirectorFactory>
----

After in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
  <scoreDirectorFactory>
    <scoreDrl>org/optaplanner/examples/cloudbalancing/solver/cloudBalancingScoreRules.drl</scoreDrl>
  </scoreDirectorFactory>
----

For a bendable score, also move the `bendableHardLevelsSize` and `bendableSoftLevelsSize` lines from the solver configuration XML
into the `@PlanningScore` annotation on your domain class.

Before in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
  <scoreDirectorFactory>
    <scoreDefinitionType>BENDABLE</scoreDefinitionType>
    <bendableHardLevelsSize>1</bendableHardLevelsSize>
    <bendableSoftLevelsSize>2</bendableSoftLevelsSize>
    <scoreDrl>org/optaplanner/examples/projectjobscheduling/solver/projectJobSchedulingScoreRules.drl</scoreDrl>
  </scoreDirectorFactory>
----

After in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
  <scoreDirectorFactory>
    <scoreDrl>org/optaplanner/examples/projectjobscheduling/solver/projectJobSchedulingScoreRules.drl</scoreDrl>
  </scoreDirectorFactory>
----

Before in `*.java`:
[source, java]
----
    @PlanningScore
    private BendableScore score;
----

After in `*.java`:
[source, java]
----
    @PlanningScore(bendableHardLevelsSize = 1, bendableSoftLevelsSize = 2)
    private BendableScore score;
----

In the rare case that you're using a custom score, also move its declaration into the domain:

After in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
    <scoreDefinitionClass>...MyCustomScoreDefinition</scoreDefinitionClass>
----

After in `*.java`:
[source, java]
----
    @PlanningScore(scoreDefinitionClass = MyCustomScoreDefinition.class)
----

[.upgrade-recipe-minor.upgrade-recipe-public-api]
===  `@PlanningVariable` on primitive types: no longer supported

An `@PlanningVariable` annotation on a primitive type such as `int` or `long` (instead of `Integer` or `Long`)
now fails fast instead of causing an inferior result.
The use of a primitive type caused the Construction Heuristics to presume the variable is already initialized
(because it's not null and it might be form of Repeated Planning),
which lead to inferior results.
It was hard to diagnose the cause of that issue for many users, so now this inferior approach fails fast with a clear message.

Before in `*.java`:
[source, java]
----
    private int delay;

    @PlanningVariable(valueRangeProviderRefs = {"delayRange"})
    public int getDelay() {
        return delay;
    }

    public void setDelay(int delay) {
        this.delay = delay;
    }
----

After in `*.java`:
[source, java]
----
    private Integer delay;

    @PlanningVariable(valueRangeProviderRefs = {"delayRange"})
    public Integer getDelay() {
        return delay;
    }

    public void setDelay(Integer delay) {
        this.delay = delay;
    }
----
