= Upgrade recipe 8
:awestruct-description: Upgrade to OptaPlanner 8 from a previous version.
:awestruct-layout: upgradeRecipeBase
:awestruct-priority: 0.5
:awestruct-upgrade_recipe_version: 8


// TODO Once 8.0.0.Beta1 is out, remove these lines and add a link to this page in ./index.adoc
*OptaPlanner 8 is in _alpha_ development.
There is no use in waiting for it.
Please use and download the latest 7.x release instead.*

== From 7.39.0.Final or higher to 8.0.0.Beta1

=== Backwards incompatible changes to the public API in 7.0

Because this is a new major version number (8.0), which is the foundation for the 8.x series for the next few years,
it allows us to make backwards incompatible changes to the public API _for the long term benefit of this project_.

We kept these backwards incompatible changes to a strict minimum
and will not introduce any additional ones during the 8.x era.

Any backwards incompatible changes are annotated with a [.label.label-danger.label-as-badge.label-public-api]#Public API# badge.


//[.upgrade-recipe-major.upgrade-recipe-public-api]
//=== Java 11 or higher required
//
//If you're using JRE or JDK 8, upgrade to JDK 11 or higher.
//
//JDK 11 or higher is still available for _free_ (including security and bug fixes),
//alongside Oracle's paid subscription.
//
//* On linux, get OpenJDK from your linux software repository.
//For example on Fedora and RHEL:
//+
//[source, bash]
//----
//sudo dnf install java-11-openjdk-devel
//----
//
//* On Windows and Mac, https://adoptopenjdk.net[download OpenJDK from AdoptOpenJDK].
//
//We currently intend to support a minimal version of Java 11 throughout the entire 8.x series.


[.upgrade-recipe-major.upgrade-recipe-public-api]
=== OSGi metadata removed

==== Reason:
Due to the limited usage of OSGi and the maintenance burden it brings,
the OptaPlanner jars in the 8.x series no longer include OSGi metadata in their `META-INF/MANIFEST.MF` file.

[.upgrade-recipe-minor]
=== `filterClassList` replaced by a single filterClass

The configuration of `EntitySelector`, `ValueSelector` and `MoveSelector` now has a single filter class in both
the configuration API and the solver configuration XML.

==== Reason:
In practice, you don't need multiple selection filter classes often, and you can always replace them by a single selection
filter class which implements the logic of all of them.
Passing a single selection class now requires less boilerplate code.

Before in `*.java`:
[source, java]
----
ValueSelectorConfig valueSelectorConfig = new ValueSelectorConfig();
valueSelectorConfig.setFilterClassList(Collections.singletonList(MySelectionFilterClass.class));
----

After in `*.java`:
[source, java]
----
ValueSelectorConfig valueSelectorConfig = new ValueSelectorConfig();
valueSelectorConfig.setFilterClass(MySelectionFilterClass.class);
----

==== Replacing multiple selection filter classes with a single one

Before in `*.xml`:

[source, xml]
----
<swapMoveSelector>
  <entitySelector>
    <filterClass>com.example.FilterA</filterClass>
    <filterClass>com.example.FilterB</filterClass>
  </entitySelector>
</swapMoveSelector>
----
Before in `*.java`:

[source, java]
----
package com.example;
...
public class FilterA implements SelectionFilter<MySolution, MyPlanningEntity> {

    @Override
    public boolean accept(ScoreDirector<MySolution> scoreDirector, MyPlanningEntity selection) {
        return selection.getValue() < 500;
    }
}
----
[source, java]
----
package com.example;
...
public class FilterB implements SelectionFilter<MySolution, MyPlanningEntity> {

    @Override
    public boolean accept(ScoreDirector<MySolution> scoreDirector, MyPlanningEntity selection) {
        return selection.getOrder() == Order.ASC;
    }
}
----

After in `*.xml`

[source, xml]
----
<swapMoveSelector>
  <entitySelector>
    <filterClass>com.example.SingleEntityFilter</filterClass>
  </entitySelector>
</swapMoveSelector>
----

After in `*.java`:

[source, java]
----
package com.example;
...
public class SingleEntityFilter implements SelectionFilter<MySolution, MyPlanningEntity> {

    @Override
    public boolean accept(ScoreDirector<MySolution> scoreDirector, MyPlanningEntity selection) {
        return selection.getValue() < 500 && selection.getOrder() == Order.ASC;
    }
}
----

[.upgrade-recipe-minor]
=== `AcceptorConfig` renamed to LocalSearchAcceptorConfig

Impacts only configuration API, solver configuration XML remains intact.

==== Reason:
Naming consistency with other local-search-specific configuration classes.

Before in `*.java`:
[source, java]
----
LocalSearchPhaseConfig localSearchPhaseConfig = new LocalSearchPhaseConfig()
        .withAcceptorConfig(new AcceptorConfig().withEntityTabuSize(5));
----

After in `*.java`:
[source, java]
----
LocalSearchPhaseConfig localSearchPhaseConfig = new LocalSearchPhaseConfig()
        .withAcceptorConfig(new LocalSearchAcceptorConfig().withEntityTabuSize(5));
----

[.upgrade-recipe-minor]
=== `Custom properties` XML configuration format changes

Impact only the solver configuration XML, specifically `<scoreDirectorFactory/>`, `<moveIteratorFactory/>`,
`<moveListFactory/>`, `<partitionedSearch/>` and `<customPhase/>`.

==== Reason:
To enforce structure of the configuration XML in build time.

Before in `*.xml`:

[source, xml]
----
<partitionedSearch>
  <solutionPartitionerClass>com.example.MySolutionPartitioner</solutionPartitionerClass>
  <solutionPartitionerCustomProperties>
    <partCount>4<partCount/> <!-- a custom property -->
    <minimumProcessListSize>300<minimumProcessListSize/> <!-- a custom property -->
  </solutionPartitionerCustomProperties>
</partitionedSearch>
----

After in `*.xml`:

[source, xml]
----
<partitionedSearch>
  <solutionPartitionerClass>com.example.MySolutionPartitioner</solutionPartitionerClass>
  <solutionPartitionerCustomProperties>
    <property name="partCount" value="4"/> <!-- a custom property -->
    <property name="minimumProcessListSize" value="300"/> <!-- a custom property -->
  </solutionPartitionerCustomProperties>
</partitionedSearch>
----

[.upgrade-recipe-minor]
=== `<variableNameInclude/>` elements are now wrapped by the <variableNameIncludes/> element

Impact only the solver configuration XML, specifically the `<swapMoveSelector/>` and `<pillarSwapMoveSelector/>`.

==== Reason:
To enforce structure of the configuration XML in build time.

Before in `*.xml`:

[source, xml]
----
<swapMoveSelector>
  <variableNameInclude>variableA</variableNameInclude>
  <variableNameInclude>variableB</variableNameInclude>
</swapMoveSelector>
----

After in `*.xml`:

[source, xml]
----
<swapMoveSelector>
  <variableNameIncludes>
    <variableNameInclude>variableA</variableNameInclude>
    <variableNameInclude>variableB</variableNameInclude>
  </variableNameIncludes>
</swapMoveSelector>
----
