= Upgrade recipe 7.6
:awestruct-description: Upgrade to OptaPlanner 7.6 from a previous version.
:awestruct-layout: upgradeRecipeBase
:awestruct-priority: 0.5
:awestruct-upgrade_recipe_version: 7.6

== From 7.5.0.Final to 7.6.0.Final

[.upgrade-recipe-minor]
=== `PlannerBenchmark`: new method `benchmarkAndShowReportInBrowser()`

If you're running local benchmarks, this new method will save time by open the report automatically.

Before in `*.java`:
[source, java]
----
plannerBenchmark.benchmark();
// Afterwards manually find the benchmark dir to open the report
----

After in `*.java`:
[source, java]
----
plannerBenchmark.benchmarkAndShowReportInBrowser();
----

[.upgrade-recipe-minor]
=== `ConstraintMatchAwareIncrementalScoreCalculator`: `Indictment.addConstraintMatch()` changed

This only applies if you're extending `ConstraintMatchAwareIncrementalScoreCalculator`
and you do not simply return `null` in `getIndictmentMap()`.

The method `Indictment.addConstraintMatch(ConstraintMatch)` now returns void instead of a boolean.
If the same `ConstraintMatch` is added twice, it now fails fast instead of returning false.
If the same `ConstraintMatch` has the same justification twice,
it must now be added to that justification's `Indictment` only once.
