= Upgrade recipe 7.1
:awestruct-description: Upgrade to OptaPlanner 7.1 from a previous version.
:awestruct-layout: upgradeRecipeBase
:awestruct-priority: 0.5
:awestruct-upgrade_recipe_version: 7.1

== From 7.1.0.Beta2 to 7.1.0.Beta3

[.upgrade-recipe-minor]
=== `<valueSelector>`: `variableName` is now an attribute

When power tweaking move selectors, such as `<changeMoveSelector>`,
in a use case with multiple planning variables,
the `<variableName>` XML element has been replaced by a `variableName="..."` XML attribute.
This reduces the solver configuration verbosity.
For backwards compatibility, the old way is still supported in the 7.x series.

Before in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
  <valueSelector>
    <variableName>room</variableName>
  </valueSelector>
----

After in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
  <valueSelector variableName="room"/>
----

[.upgrade-recipe-minor]
=== Construction Heuristic: multiple variable power tweaking simplified

It's now easier to configure construction heuristics that scale better for multiple variables,
but assigning one variable at a time.

Before in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
  <constructionHeuristic>
    <queuedEntityPlacer>
      <entitySelector id="placerEntitySelector"/>
      <changeMoveSelector>
        <entitySelector mimicSelectorRef="placerEntitySelector"/>
        <valueSelector variableName="period"/>
      </changeMoveSelector>
      <changeMoveSelector>
        <entitySelector mimicSelectorRef="placerEntitySelector"/>
        <valueSelector variableName="room"/>
      </changeMoveSelector>
    </queuedEntityPlacer>
  </constructionHeuristic>
----

After in `*SolverConfig.xml` and `*BenchmarkConfig.xml`:
[source, xml]
----
  <constructionHeuristic>
    <constructionHeuristicType>FIRST_FIT</constructionHeuristicType>
    <changeMoveSelector>
      <valueSelector variableName="period"/>
    </changeMoveSelector>
    <changeMoveSelector>
      <valueSelector variableName="room"/>
    </changeMoveSelector>
  </constructionHeuristic>
----
