= Training
:jbake-type: normalBase
:jbake-description: Complete these labs and workshops to improve your OptaPlanner experience.
:jbake-priority: 0.4
:showtitle:

== Getting started with Optaplanner and Quarkus, a step-by-step guide

Check out https://github.com/KIE-Learning/knapsack-optaplanner-quarkus[this guide] to quickly (15-25min) learn:

* How to solve a _knapsack problem_ with OptaPlanner.
* OptaPlanner core concepts and how to apply them in a use case
* How to expose your service as a REST application on Quarkus.
* How to deploy that application in the cloud on OpenShift.

https://github.com/KIE-Learning/knapsack-optaplanner-quarkus[*Start the free training now*]

== Training zip (legacy)

=== What is it?

The optaplanner-training teaches OptaPlanner through a number of labs.
Each lab has an assignment with clear goals, initial code and a solution.

https://download.jboss.org/optaplanner/training/optaplanner-training-7.0.0.Beta4-training-4.zip[*Download optaplanner-training-7.0.0.Beta4-training-4.zip*]

=== Usage

. Download and unzip `optaplanner-training-*.zip`
. Open `instructions/training.html` and follow those instructions.

=== Source

The source code which _generates_ that training zip is in https://github.com/kiegroup/optaplanner-training[the optaplanner-training GitHub repository].
